export const initialState = {
    AgesAllowed: [false, false, false, true],
    Alcohol: [false, false, true],
    Ambience: [false, false, false, false, false, false, false, false, false],
    BYOBCorkage: [true, false, false],
    BestNights: [false, false, false, false, false, false, false],
    BikeParking: [-1],
    BusinessAcceptsBitcoin: [-1],
    BusinessAcceptsCreditCards: [-1],
    BusinessParking: [false, false, false, false, false],
    Caters: [-1],
    CoatCheck: [-1],
    DietaryRestrictions: [false, false, false, false],
    DogsAllowed: [-1],
    DriveThru: [-1],
    GoodForDancing: [-1],
    GoodForKids: [-1],
    GoodForMeal: [false, false, false, false, false, false],
    HairSpecializesIn: [-1],
    HappyHour: [-1],
    HasTV: [-1],
    Music: [false, false, false, false, false, false],
    NoiseLevel: [false, false, false, false, true],
    Open24Hours: [-1],
    OutdoorSeating: [-1],
    RestaurantsAttire: [false, false, false, true],
    RestaurantsCounterService: [-1],
    RestaurantsDelivery: [-1],
    RestaurantsGoodForGroups: [-1],
    RestaurantsPriceRange2: [-1],
    RestaurantsReservations: [-1],
    RestaurantsTableService: [-1],
    RestaurantsTakeOut: [-1],
    Smoking: [-1],
    WheelchairAccessible: [-1],
    WiFi: [true, false, false]
};

export const stateList = [
    'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 
    'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 
    'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 
    'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
]